use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, Attribute, DeriveInput, Ident, Token};

/// `#[derive(DistributedTypestate)]` — 状態機械の宣言から型安全な
/// 分散状態遷移コードを自動生成する。
///
/// # 使い方
///
/// ```rust,ignore
/// #[derive(DistributedTypestate)]
/// enum ServerState {
///     #[transition(start => Starting)]
///     Stopped,
///
///     #[transition(started => Running)]
///     Starting,
///
///     #[transition(stop => Stopping, restart => Starting)]
///     Running,
///
///     #[transition(stopped => Stopped)]
///     Stopping,
/// }
/// ```
///
/// # 生成されるもの
///
/// - マーカー型: `ServerStateStopped`, `ServerStateStarting`, etc.
/// - リソースラッパー型: `Server<State>` (enum名から "State" を除いた名前)
/// - 遷移メソッド: `Server<ServerStateStopped>::start(self, &backend)`
/// - Handle enum: `ServerStateHandle`
/// - Load関数: `load_server_state(&backend, id)`
/// - Create関数: `create_server_state(&backend, id)`
#[proc_macro_derive(DistributedTypestate, attributes(transition))]
pub fn derive_distributed_typestate(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match impl_distributed_typestate(&input) {
        Ok(tokens) => tokens.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

/// transition属性からmethod_name, target_stateのペアを抽出
struct TransitionDef {
    method_name: Ident,
    target_state: Ident,
}

/// enum variantの#[transition(...)]をパースする
fn parse_transitions(attrs: &[Attribute]) -> syn::Result<Vec<TransitionDef>> {
    let mut transitions = Vec::new();

    for attr in attrs {
        if !attr.path().is_ident("transition") {
            continue;
        }

        // #[transition(method1 => Target1, method2 => Target2)]
        attr.parse_args_with(|input: syn::parse::ParseStream| {
            loop {
                let method_name: Ident = input.parse()?;
                input.parse::<Token![=>]>()?;
                let target_state: Ident = input.parse()?;

                transitions.push(TransitionDef {
                    method_name,
                    target_state,
                });

                if input.peek(Token![,]) {
                    input.parse::<Token![,]>()?;
                    if input.is_empty() {
                        break;
                    }
                } else {
                    break;
                }
            }
            Ok(())
        })?;
    }

    Ok(transitions)
}

fn impl_distributed_typestate(input: &DeriveInput) -> syn::Result<proc_macro2::TokenStream> {
    let enum_name = &input.ident;

    // enumのバリアントを取得
    let data_enum = match &input.data {
        syn::Data::Enum(e) => e,
        _ => {
            return Err(syn::Error::new_spanned(
                input,
                "DistributedTypestate can only be derived for enums",
            ))
        }
    };

    // リソース型名: enum名から末尾のStateを除いたもの
    // 例、JobState → Job, ServerState → Server
    let enum_str = enum_name.to_string();
    let resource_name = if enum_str.ends_with("State") {
        format_ident!("{}", &enum_str[..enum_str.len() - 5])
    } else {
        format_ident!("{}Resource", enum_name)
    };

    // 各バリアントの情報を収集
    struct VariantInfo {
        variant_name: Ident,
        marker_type: Ident,
        state_str: String,
        transitions: Vec<TransitionDef>,
    }

    let mut variants = Vec::new();

    for variant in &data_enum.variants {
        if !variant.fields.is_empty() {
            return Err(syn::Error::new_spanned(
                variant,
                "DistributedTypestate variants must be unit variants (no fields)",
            ));
        }

        let variant_name = variant.ident.clone();
        let marker_type = format_ident!("{}{}", enum_name, variant_name);
        let state_str = to_snake_case(&variant_name.to_string());
        let transitions = parse_transitions(&variant.attrs)?;

        variants.push(VariantInfo {
            variant_name,
            marker_type,
            state_str,
            transitions,
        });
    }

    // コード生成

    // マーカー型の生成
    let marker_types: Vec<_> = variants
        .iter()
        .map(|v| {
            let marker = &v.marker_type;
            let doc = format!(
                "State marker: {} is in the \"{}\" state",
                enum_name, v.state_str
            );
            quote! {
                #[doc = #doc]
                pub struct #marker;
            }
        })
        .collect();

    // リソース型: orphan rule を回避するため、マクロが直接生成する
    let resource_type_doc = format!(
        "Distributed Typestate resource for `{}`.\n\n\
         Generated by `#[derive(DistributedTypestate)]`.",
        enum_name
    );

    // 各状態の遷移メソッド生成
    let transition_impls: Vec<_> = variants
        .iter()
        .map(|v| {
            let from_marker = &v.marker_type;
            let from_state_str = &v.state_str;

            let methods: Vec<_> = v
                .transitions
                .iter()
                .map(|t| {
                    let method = &t.method_name;
                    let to_marker = format_ident!("{}{}", enum_name, t.target_state);
                    let to_state_str = to_snake_case(&t.target_state.to_string());

                    let doc = format!(
                        "Transition: {} → {} (CAS: \"{}\" → \"{}\")",
                        v.variant_name, t.target_state, from_state_str, to_state_str,
                    );

                    quote! {
                        #[doc = #doc]
                        pub fn #method(
                            self,
                            backend: &impl dist_typestate::backend::StateBackend,
                        ) -> Result<#resource_name<#to_marker>, dist_typestate::error::TransitionError> {
                            let new_rev = backend.compare_and_transition(
                                &self.id,
                                #from_state_str,
                                self.revision,
                                #to_state_str,
                            )?;
                            Ok(#resource_name {
                                id: self.id,
                                revision: new_rev,
                                _state: std::marker::PhantomData,
                            })
                        }
                    }
                })
                .collect();

            // 共通メソッド id, revisionも各状態で使えるようにする
            quote! {
                impl #resource_name<#from_marker> {
                    #(#methods)*
                }
            }
        })
        .collect();

    // Handle enum生成
    let handle_name = format_ident!("{}Handle", enum_name);

    let handle_variants: Vec<_> = variants
        .iter()
        .map(|v| {
            let variant_name = &v.variant_name;
            let marker = &v.marker_type;
            quote! {
                #variant_name(#resource_name<#marker>)
            }
        })
        .collect();

    // load関数生成
    let load_fn_name = format_ident!("load_{}", to_snake_case(&enum_str));

    let load_arms: Vec<_> = variants
        .iter()
        .map(|v| {
            let state_str = &v.state_str;
            let variant_name = &v.variant_name;
            quote! {
                #state_str => Ok(#handle_name::#variant_name(#resource_name {
                    id: id.to_string(),
                    revision,
                    _state: std::marker::PhantomData,
                }))
            }
        })
        .collect();

    // create関数生成
    let create_fn_name = format_ident!("create_{}", to_snake_case(&enum_str));
    let initial_state_str = &variants[0].state_str;
    let initial_marker = &variants[0].marker_type;

    let output = quote! {
        //  マーカー型
        #(#marker_types)*

        // リソース型(マクロが自己完結して生成)
        #[doc = #resource_type_doc]
        pub struct #resource_name<State> {
            id: String,
            revision: u64,
            _state: std::marker::PhantomData<State>,
        }

        impl<S> #resource_name<S> {
            /// リソースIDを取得
            pub fn id(&self) -> &str {
                &self.id
            }

            /// 現在のrevisionを取得
            pub fn revision(&self) -> u64 {
                self.revision
            }
        }

        impl<S> std::fmt::Debug for #resource_name<S> {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.debug_struct(stringify!(#resource_name))
                    .field("id", &self.id)
                    .field("revision", &self.revision)
                    .field("state", &std::any::type_name::<S>())
                    .finish()
            }
        }

        // 遷移メソッド
        #(#transition_impls)*

        // Handle enum
        #[derive(Debug)]
        pub enum #handle_name {
            #(#handle_variants),*
        }

        // load関数
        pub fn #load_fn_name(
            backend: &impl dist_typestate::backend::StateBackend,
            id: &str,
        ) -> Result<#handle_name, dist_typestate::error::TransitionError> {
            let (state, revision) = backend.load(id)?;

            match state.as_str() {
                #(#load_arms,)*
                other => Err(dist_typestate::error::TransitionError::BackendError(
                    format!("unknown state: {}", other)
                )),
            }
        }

        // create関数
        pub fn #create_fn_name(
            backend: &impl dist_typestate::backend::StateBackend,
            id: &str,
        ) -> Result<#resource_name<#initial_marker>, dist_typestate::error::TransitionError> {
            let revision = backend.create(id, #initial_state_str)?;
            Ok(#resource_name {
                id: id.to_string(),
                revision,
                _state: std::marker::PhantomData,
            })
        }
    };

    Ok(output)
}

/// PascalCaseからsnake_caseへ変換
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        } else {
            result.push(ch);
        }
    }
    result
}
